# Generated by Django 3.2.3 on 2021-06-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='search_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Search_Done'),
        ),
    ]
